#!/usr/bin/env python3
"""
Inventory Management REST API
Generated by EVEZ Expansion Engine
Receipt: RCPT-20260408045124
"""

from flask import Flask, jsonify, request
from datetime import datetime
import uuid

app = Flask(__name__)

# In-memory database
inventory = {}
categories = {}

@app.route('/api/health', methods=['GET'])
def health():
    return jsonify({'status': 'healthy', 'timestamp': datetime.utcnow().isoformat()})

@app.route('/api/items', methods=['GET'])
def get_items():
    return jsonify({'items': list(inventory.values()), 'count': len(inventory)})

@app.route('/api/items/<item_id>', methods=['GET'])
def get_item(item_id):
    item = inventory.get(item_id)
    if not item:
        return jsonify({'error': 'Item not found'}), 404
    return jsonify(item)

@app.route('/api/items', methods=['POST'])
def create_item():
    data = request.json
    item_id = str(uuid.uuid4())[:8]
    item = {
        'id': item_id,
        'name': data.get('name'),
        'quantity': data.get('quantity', 0),
        'category': data.get('category'),
        'price': data.get('price', 0.0),
        'created_at': datetime.utcnow().isoformat()
    }
    inventory[item_id] = item
    return jsonify(item), 201

@app.route('/api/items/<item_id>', methods=['PUT'])
def update_item(item_id):
    if item_id not in inventory:
        return jsonify({'error': 'Item not found'}), 404
    data = request.json
    inventory[item_id].update(data)
    inventory[item_id]['updated_at'] = datetime.utcnow().isoformat()
    return jsonify(inventory[item_id])

@app.route('/api/items/<item_id>', methods=['DELETE'])
def delete_item(item_id):
    if item_id not in inventory:
        return jsonify({'error': 'Item not found'}), 404
    del inventory[item_id]
    return jsonify({'status': 'deleted'})

@app.route('/api/categories', methods=['GET'])
def get_categories():
    return jsonify({'categories': list(categories.values())})

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)