#!/bin/bash
# Daily Journal - Summarizes all work done each day
# Run manually: ./daily_journal.sh
# Scheduled: 23:55 daily

WORKSPACE="/root/.openclaw/workspace"
JOURNAL_DIR="$WORKSPACE/journal"
LOGS_DIR="$WORKSPACE/logs"
EXPERIMENTS_DIR="$WORKSPACE/experiments"

mkdir -p "$JOURNAL_DIR"

TODAY=$(date +%Y-%m-%d)
JOURNAL_FILE="$JOURNAL_DIR/$TODAY.md"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

generate_journal() {
    log "Generating daily journal..."
    
    # Start journal
    CONTENT="# Daily Journal - $TODAY
Generated: $(date '+%Y-%m-%d %H:%M:%S')

## Commands Run Today

"
    
    # Get today's log entries
    TODAY_LOG="$LOGS_DIR/quantum_sweep_$TODAY.log"
    if [ -f "$TODAY_LOG" ]; then
        CONTENT+="### Quantum Sweeps
```
"
        CONTENT+=$(tail -50 "$TODAY_LOG" 2>/dev/null)
        CONTENT+="
```
"
    fi
    
    # Healthcheck results
    HEALTH_LOG="$LOGS_DIR/health_$TODAY.log"
    if [ -f "$HEALTH_LOG" ]; then
        CONTENT+="
### Health Checks
```
"
        CONTENT+=$(tail -20 "$HEALTH_LOG" 2>/dev/null)
        CONTENT+="
```
"
    fi
    
    # Files created/modified today
    CONTENT+="
## Files Created/Modified

"
    for dir in "$WORKSPACE/skills" "$WORKSPACE/ops" "$WORKSPACE/ci" "$WORKSPACE/experiments"; do
        if [ -d "$dir" ]; then
            NEW_FILES=$(find "$dir" -type f -mtime -1 2>/dev/null | head -10)
            if [ -n "$NEW_FILES" ]; then
                CONTENT+="### $dir
"
                CONTENT+="$NEW_FILES

"
            fi
        fi
    done
    
    # Quantum experiment summary
    METRICS_CSV="$EXPERIMENTS_DIR/quantum_metrics.csv"
    if [ -f "$METRICS_CSV" ]; then
        TODAY_EXPERIMENTS=$(grep "$TODAY" "$METRICS_CSV" | wc -l)
        TODAY_SUCCESS=$(grep "$TODAY" "$METRICS_CSV" | grep "True" | wc -l)
        
        CONTENT+="
## Quantum Experiments Today

- Total runs: $TODAY_EXPERIMENTS
- Successful: $TODAY_SUCCESS
- Failed: $((TODAY_EXPERIMENTS - TODAY_SUCCESS))

"
    fi
    
    # Summary
    CONTENT+="
## Summary

"
    CONTENT+="- Quantum productivity suite: Active
- Qiskit: $(python3 -c "import qiskit; print(qiskit.__version__)" 2>/dev/null || echo "N/A")
- Skills deployed: quantum-ez, healthcheck, ci-sidecar

---
*Generated by KiloClaw R&D Assistant*
"
    
    echo "$CONTENT" > "$JOURNAL_FILE"
    log "Journal written to $JOURNAL_FILE"
    
    # Show what was generated
    echo "=== Journal Summary ==="
    echo "Total lines: $(wc -l < "$JOURNAL_FILE")"
    echo "File size: $(du -h "$JOURNAL_FILE" | cut -f1)"
}

# Run
generate_journal